import { Inter } from "next/font/google";
import "../../app/globals.css";
import Navbar from '@/components/module/navbar'
import Footer from '@/components/module/footer'
// import { Toaster } from 'sonner'
// import { Providers } from "../../redux/Providers"

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Mama Recipe",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    // <Providers>
    // <html lang="en">
    // <body className={inter.className}>
    <>
      <Navbar />
      {children}
      <Footer />
    </>
    // {/* <Toaster richColors position="top-center" /> */}
    // </body>
    // </html>
    // </Providers> 
  );
}
