"use client"

import { Inter } from "next/font/google";
import "../../app/globals.css";
import { Toaster } from 'sonner'
import { Provider } from 'react-redux';
import store from '../../redux/store';


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider store={store}>
                    {children}
                </Provider>
                <Toaster richColors position="top-center" />
            </body>
            {/* <Toaster richColors position="top-center" /> */}
        </html>
    )
}
